# 01_CO‚ÇÇ Emission Prediction üöóüí®

---


### üîó Live Demo:
[Click here to test the model](https://your-streamlit-app-link.com)  

### üìå How to Use:
1. Open the **live demo link** above.
2. Enter the required values (Engine Size, Cylinders, Fuel Consumption, etc.).
3. Click the **Predict** button to get the CO‚ÇÇ emission estimate.
4. The model will process your input and display the prediction instantly.

---
üîç **For Code & Implementation Details:**  
Check out the **GitHub Repository** [here](https://your-github-repo-link.com).  

‚ö° **Note:** This notebook contains the full workflow (data exploration, training, and inference). You can explore the entire process or just produce inference using live demo link.  

---

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
# reading dataset
df=pd.read_csv("CO2_Emissions_Canada.csv")
df.head(20)

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
0,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221
2,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136
3,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255
4,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244
5,ACURA,RLX,MID-SIZE,3.5,6,AS6,Z,11.9,7.7,10.0,28,230
6,ACURA,TL,MID-SIZE,3.5,6,AS6,Z,11.8,8.1,10.1,28,232
7,ACURA,TL AWD,MID-SIZE,3.7,6,AS6,Z,12.8,9.0,11.1,25,255
8,ACURA,TL AWD,MID-SIZE,3.7,6,M6,Z,13.4,9.5,11.6,24,267
9,ACURA,TSX,COMPACT,2.4,4,AS5,Z,10.6,7.5,9.2,31,212
10,ACURA,TSX,COMPACT,2.4,4,M6,Z,11.2,8.1,9.8,29,225
11,ACURA,TSX,COMPACT,3.5,6,AS5,Z,12.1,8.3,10.4,27,239
12,ALFA ROMEO,4C,TWO-SEATER,1.8,4,AM6,Z,9.7,6.9,8.4,34,193
13,ASTON MARTIN,DB9,MINICOMPACT,5.9,12,A6,Z,18.0,12.6,15.6,18,359
14,ASTON MARTIN,RAPIDE,SUBCOMPACT,5.9,12,A6,Z,18.0,12.6,15.6,18,359
15,ASTON MARTIN,V8 VANTAGE,TWO-SEATER,4.7,8,AM7,Z,17.4,11.3,14.7,19,338
16,ASTON MARTIN,V8 VANTAGE,TWO-SEATER,4.7,8,M6,Z,18.1,12.2,15.4,18,354
17,ASTON MARTIN,V8 VANTAGE S,TWO-SEATER,4.7,8,AM7,Z,17.4,11.3,14.7,19,338
18,ASTON MARTIN,V8 VANTAGE S,TWO-SEATER,4.7,8,M6,Z,18.1,12.2,15.4,18,354
19,ASTON MARTIN,VANQUISH,MINICOMPACT,5.9,12,A6,Z,18.0,12.6,15.6,18,359

In [ ]:
df.shape

(7385, 12)

In [ ]:
df.info

<bound method DataFrame.info of        Make        Model   Vehicle Class  Engine Size(L)  Cylinders  \
0     ACURA          ILX         COMPACT             2.0          4
1     ACURA          ILX         COMPACT             2.4          4
2     ACURA   ILX HYBRID         COMPACT             1.5          4
3     ACURA      MDX 4WD     SUV - SMALL             3.5          6
4     ACURA      RDX AWD     SUV - SMALL             3.5          6
...     ...          ...             ...             ...        ...
7380  VOLVO  XC40 T5 AWD     SUV - SMALL             2.0          4
7381  VOLVO  XC60 T5 AWD     SUV - SMALL             2.0          4
7382  VOLVO  XC60 T6 AWD     SUV - SMALL             2.0          4
7383  VOLVO  XC90 T5 AWD  SUV - STANDARD             2.0          4
7384  VOLVO  XC90 T6 AWD  SUV - STANDARD             2.0          4

     Transmission Fuel Type  Fuel Consumption City (L/100 km)  \
0             AS5         Z                               9.9
1              M6         Z                              11.2
2             AV7         Z                               6.0
3             AS6         Z                              12.7
4             AS6         Z                              12.1
...           ...       ...                               ...
7380          AS8         Z                              10.7
7381          AS8         Z                              11.2
7382          AS8         Z                              11.7
7383          AS8         Z                              11.2
7384          AS8         Z                              12.2

      Fuel Consumption Hwy (L/100 km)  Fuel Consumption Comb (L/100 km)  \
0                                 6.7                               8.5
1                                 7.7                               9.6
2                                 5.8                               5.9
3                                 9.1                              11.1
4                                 8.7                              10.6
...                               ...                               ...
7380                              7.7                               9.4
7381                              8.3                               9.9
7382                              8.6                              10.3
7383                              8.3                               9.9
7384                              8.7                              10.7

      Fuel Consumption Comb (mpg)  CO2 Emissions(g/km)
0                              33                  196
1                              29                  221
2                              48                  136
3                              25                  255
4                              27                  244
...                           ...                  ...
7380                           30                  219
7381                           29                  232
7382                           27                  240
7383                           29                  232
7384                           26                  248

[7385 rows x 12 columns]>

In [ ]:
##summary of the dataset
df.describe()

,Engine Size(L),Cylinders,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
count,7385.000000,7385.000000,7385.000000,7385.000000,7385.000000,7385.000000,7385.000000
mean,3.160068,5.615030,12.556534,9.041706,10.975071,27.481652,250.584699
std,1.354170,1.828307,3.500274,2.224456,2.892506,7.231879,58.512679
min,0.900000,3.000000,4.200000,4.000000,4.100000,11.000000,96.000000
25%,2.000000,4.000000,10.100000,7.500000,8.900000,22.000000,208.000000
50%,3.000000,6.000000,12.100000,8.700000,10.600000,27.000000,246.000000
75%,3.700000,6.000000,14.600000,10.200000,12.600000,32.000000,288.000000
max,8.400000,16.000000,30.600000,20.600000,26.100000,69.000000,522.000000

In [ ]:
##Missing Values
df.isnull().sum()

Make                                0
Model                               0
Vehicle Class                       0
Engine Size(L)                      0
Cylinders                           0
Transmission                        0
Fuel Type                           0
Fuel Consumption City (L/100 km)    0
Fuel Consumption Hwy (L/100 km)     0
Fuel Consumption Comb (L/100 km)    0
Fuel Consumption Comb (mpg)         0
CO2 Emissions(g/km)                 0
dtype: int64

### Insights and observation
The dataset has no missing values

In [ ]:
df.head(2)

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
0,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221

In [ ]:
## List down all the columns names
df.columns

Index(['Make', 'Model', 'Vehicle Class', 'Engine Size(L)', 'Cylinders',
       'Transmission', 'Fuel Type', 'Fuel Consumption City (L/100 km)',
       'Fuel Consumption Hwy (L/100 km)', 'Fuel Consumption Comb (L/100 km)',
       'Fuel Consumption Comb (mpg)', 'CO2 Emissions(g/km)'],
      dtype='object')

In [ ]:
df['Make'].unique()

array(['ACURA', 'ALFA ROMEO', 'ASTON MARTIN', 'AUDI', 'BENTLEY', 'BMW',
       'BUICK', 'CADILLAC', 'CHEVROLET', 'CHRYSLER', 'DODGE', 'FIAT',
       'FORD', 'GMC', 'HONDA', 'HYUNDAI', 'INFINITI', 'JAGUAR', 'JEEP',
       'KIA', 'LAMBORGHINI', 'LAND ROVER', 'LEXUS', 'LINCOLN', 'MASERATI',
       'MAZDA', 'MERCEDES-BENZ', 'MINI', 'MITSUBISHI', 'NISSAN',
       'PORSCHE', 'RAM', 'ROLLS-ROYCE', 'SCION', 'SMART', 'SRT', 'SUBARU',
       'TOYOTA', 'VOLKSWAGEN', 'VOLVO', 'GENESIS', 'BUGATTI'],
      dtype=object)

In [ ]:
df['Vehicle Class'].unique()

array(['COMPACT', 'SUV - SMALL', 'MID-SIZE', 'TWO-SEATER', 'MINICOMPACT',
       'SUBCOMPACT', 'FULL-SIZE', 'STATION WAGON - SMALL',
       'SUV - STANDARD', 'VAN - CARGO', 'VAN - PASSENGER',
       'PICKUP TRUCK - STANDARD', 'MINIVAN', 'SPECIAL PURPOSE VEHICLE',
       'STATION WAGON - MID-SIZE', 'PICKUP TRUCK - SMALL'], dtype=object)

In [ ]:
df['Cylinders'].unique()

array([ 4,  6, 12,  8, 10,  3,  5, 16])

In [ ]:
df['Transmission'].unique()

array(['AS5', 'M6', 'AV7', 'AS6', 'AM6', 'A6', 'AM7', 'AV8', 'AS8', 'A7',
       'A8', 'M7', 'A4', 'M5', 'AV', 'A5', 'AS7', 'A9', 'AS9', 'AV6',
       'AS4', 'AM5', 'AM8', 'AM9', 'AS10', 'A10', 'AV10'], dtype=object)



### **Understanding the Code Format**  
Each transmission code consists of:  
- **A / M / AS / AM / AV** ‚Üí The type of transmission  
- **Number (4, 5, 6, 7, etc.)** ‚Üí The number of gears  

### **Transmission Type Breakdown**  
- **A** ‚Üí Automatic transmission (Traditional torque-converter automatic)  
- **M** ‚Üí Manual transmission  
- **AS** ‚Üí Automated Sequential transmission (Automated Manual Transmission or Dual-Clutch Transmission)  
- **AM** ‚Üí Automated Manual transmission (Similar to AS but sometimes used differently by manufacturers)  
- **AV** ‚Üí Continuously Variable Transmission (CVT)  

### **Examples and Their Meanings**  
- **M6** ‚Üí 6-speed Manual transmission  
- **A6** ‚Üí 6-speed Automatic transmission  
- **AS5** ‚Üí 5-speed Automated Sequential transmission  
- **AM6** ‚Üí 6-speed Automated Manual transmission  
- **AV7** ‚Üí 7-speed CVT (Continuously Variable Transmission)  
- **A10** ‚Üí 10-speed Automatic transmission  
- **AS8** ‚Üí 8-speed Dual-Clutch or Automated Sequential transmission  
- **AV10** ‚Üí 10-speed CVT  

### **Summary**  
- **M** ‚Üí Manual  
- **A** ‚Üí Automatic  
- **AS / AM** ‚Üí Automated versions of Manual Transmission (e.g., Dual-Clutch or Single-Clutch Automated Manual)  
- **AV** ‚Üí CVT

In [ ]:
df['Fuel Type'].unique()

array(['Z', 'D', 'X', 'E', 'N'], dtype=object)

Z ‚Üí Zero-emission vehicle (ZEV), such as electric (EVs) or hydrogen fuel cell vehicles

X ‚Üí Unknown or other fuel type (sometimes used for hybrid vehicles)

D ‚Üí Diesel fuel

E ‚Üí Ethanol or flex-fuel (E85, for example)

N ‚Üí Natural gas (CNG or LNG)

In [ ]:
## Duplicate records
df[df.duplicated()]

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
1075,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244
1076,ACURA,RLX,MID-SIZE,3.5,6,AS6,Z,11.9,7.7,10.0,28,230
1081,ALFA ROMEO,4C,TWO-SEATER,1.8,4,AM6,Z,9.7,6.9,8.4,34,193
1082,ASTON MARTIN,DB9,MINICOMPACT,5.9,12,A6,Z,18.0,12.6,15.6,18,359
1084,ASTON MARTIN,V8 VANTAGE,TWO-SEATER,4.7,8,AM7,Z,17.4,11.3,14.7,19,338
...,...,...,...,...,...,...,...,...,...,...,...,...
7356,TOYOTA,Tundra,PICKUP TRUCK - STANDARD,5.7,8,AS6,X,17.7,13.6,15.9,18,371
7365,VOLKSWAGEN,Golf GTI,COMPACT,2.0,4,M6,X,9.8,7.3,8.7,32,203
7366,VOLKSWAGEN,Jetta,COMPACT,1.4,4,AS8,X,7.8,5.9,7.0,40,162
7367,VOLKSWAGEN,Jetta,COMPACT,1.4,4,M6,X,7.9,5.9,7.0,40,163
7368,VOLKSWAGEN,Jetta GLI,COMPACT,2.0,4,AM7,X,9.3,7.2,8.4,34,196

In [ ]:
## Remove the duplicates
df.drop_duplicates(inplace=True)

In [ ]:
df.shape

(6282, 12)

In [ ]:
print(df.dtypes)  # Check column data types

Make                                 object
Model                                object
Vehicle Class                        object
Engine Size(L)                      float64
Cylinders                             int64
Transmission                         object
Fuel Type                            object
Fuel Consumption City (L/100 km)    float64
Fuel Consumption Hwy (L/100 km)     float64
Fuel Consumption Comb (L/100 km)    float64
Fuel Consumption Comb (mpg)           int64
CO2 Emissions(g/km)                   int64
dtype: object

In [ ]:
print(df.select_dtypes(include=['object']).nunique())  # Show unique counts for object (categorical) columns

Make               42
Model            2053
Vehicle Class      16
Transmission       27
Fuel Type           5
dtype: int64

In [ ]:
## Correlation
correlation_matrix = df.corr()
print(correlation_matrix)

ValueError: could not convert string to float: 'ACURA'